### ISSUE TITLE
Fails to generate the Allure report: Cannot find package 'xss' imported from .../node_modules/@allurereport/web-commons/dist/sanitizeHtml.js

### ISSUE THREAD

**Issue by plagov** [allure-framework/allure3#57]
I'm installing the Allure Report 3 and the Awesome plugin during my Azure Pipelines jobs as follows:
```yml
  - task: Npm@1
    displayName: 'Add Allure package'
    inputs:
      command: 'custom'
      customCommand: 'add allure'
      
  - task: Npm@1
    displayName: 'Add Allure Report Awesome Plugin'
    inputs:
      command: 'custom'
      customCommand: 'add @allurereport/plugin-awesome'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      
  - task: PowerShell@2
    displayName: 'Generate Allure Report'
    condition: succeededOrFailed()
    inputs:
      targetType: 'inline'
      script: 'npx allure awesome bin/Debug/net8.0/allure-results --single-file'
      workingDirectory: '$(Build.SourcesDirectory)'
```

When the job reaches the `Generate Allure Report` task, it fails with an exception:
```
node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'xss' imported from /home/ansible/myagent/_work/125/s/node_modules/@allurereport/web-commons/dist/sanitizeHtml.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.18.1
```
The issue first appeared on Monday 13.01.2025. When I run the same job on Friday 10.01.2025, it worked fine.
